version: '3.9'

services:
  client:
    build:
      context: .
    restart: always
    networks:
      - portfolio

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: always
    command: tunnel --config /etc/cloudflared/config.yml run
    networks:
      - portfolio
    volumes:
      - ./cloudflared:/etc/cloudflared

networks:
  portfolio:
    driver: bridge

